[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.0",
    "openai>=2.14.0",
    "pandas>=2.3.3",
    "scipy>=1.16.3",
    "streamlit>=1.52.2",
]
